//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DagYig.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jomolhari, 10.25pt")]
        public global::System.Drawing.Font ScanFont {
            get {
                return ((global::System.Drawing.Font)(this["ScanFont"]));
            }
            set {
                this["ScanFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float ScanFontSize {
            get {
                return ((float)(this["ScanFontSize"]));
            }
            set {
                this["ScanFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jomolhari, 25.25pt")]
        public global::System.Drawing.Font DictTibFont {
            get {
                return ((global::System.Drawing.Font)(this["DictTibFont"]));
            }
            set {
                this["DictTibFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public float DictTibFontSize {
            get {
                return ((float)(this["DictTibFontSize"]));
            }
            set {
                this["DictTibFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("265, 357")]
        public global::System.Drawing.Size ClipBoardWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["ClipBoardWindowSize"]));
            }
            set {
                this["ClipBoardWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X")]
        public string LoopHotKey {
            get {
                return ((string)(this["LoopHotKey"]));
            }
            set {
                this["LoopHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public string UseHotKey {
            get {
                return ((string)(this["UseHotKey"]));
            }
            set {
                this["UseHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1170, 584")]
        public global::System.Drawing.Size DictionaryWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["DictionaryWindowSize"]));
            }
            set {
                this["DictionaryWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jomolhari, 10.25pt")]
        public global::System.Drawing.Font DictDefFont {
            get {
                return ((global::System.Drawing.Font)(this["DictDefFont"]));
            }
            set {
                this["DictDefFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float DictDefFontSize {
            get {
                return ((float)(this["DictDefFontSize"]));
            }
            set {
                this["DictDefFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jomolhari, 10.25pt")]
        public global::System.Drawing.Font DictInputFont {
            get {
                return ((global::System.Drawing.Font)(this["DictInputFont"]));
            }
            set {
                this["DictInputFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float DictInputFontSize {
            get {
                return ((float)(this["DictInputFontSize"]));
            }
            set {
                this["DictInputFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jomolhari, 10.25pt")]
        public global::System.Drawing.Font ScanDefFont {
            get {
                return ((global::System.Drawing.Font)(this["ScanDefFont"]));
            }
            set {
                this["ScanDefFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float ScanDefFontSize {
            get {
                return ((float)(this["ScanDefFontSize"]));
            }
            set {
                this["ScanDefFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int GridRowHeight {
            get {
                return ((int)(this["GridRowHeight"]));
            }
            set {
                this["GridRowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int TibColSizeW {
            get {
                return ((int)(this["TibColSizeW"]));
            }
            set {
                this["TibColSizeW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("475")]
        public int DefColSizeW {
            get {
                return ((int)(this["DefColSizeW"]));
            }
            set {
                this["DefColSizeW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int WylieColSizeW {
            get {
                return ((int)(this["WylieColSizeW"]));
            }
            set {
                this["WylieColSizeW"] = value;
            }
        }
    }
}
